spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/product-manager"
    username: "root"
    password: "123"
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  flyway:
    url: jdbc:mariadb://localhost:3306/product-manager
    schemas: product-manager
    user: "root"
    password: "123"
    locations: classpath:db/migration
    enabled: true
logging:
  level:
    org:
      springframework:
        security: DEBUG